import React from "react";
export const img = [
  {
    src: "https://i.pinimg.com/564x/97/e6/bf/97e6bf0d8ae21916190bd3202bc56cbb.jpg",
    title: "Dean Winchester",
    content:
      " Dean Winchester (b. January 24, 1979[2] – d. 2025[3]) was a human and hunter as well as a member of the Men of Letters with his younger brother Sam. He and his brother are members of the Winchester[4] and Campbell families.[5] Through his father, Dean is the older half-brother of Adam Milligan.Dean is also the destined vessel of the Archangel Michael.[7] He and Sam are also the surrogate sons of the late Bobby Singer.[8][9] Dean is best friends with the angel Castiel, close friend to the late prophet Kevin Tran, and reluctant ally of Crowley. Dean has an ex-girlfriend, Lisa Braeden,[10] who he lived with for a year[11] when he thought Sam was in Hell. She has a child named Ben, who Dean acted as a father for during that year. Dean's biological child was an amazon named Emma.[12] He is also the former apprentice of Alastair.Both Dean and Sam were raised in the hunting life by their father, after the demon Azazel killed their mother. Dean's main role in the series is being the self-appointed guardian of Sam and often going to extreme lengths to protect him regardless of personal cost. Often in these occurrences Dean finds himself the center of a much larger picture.When he was killed by Metatron whilst using the Mark of Cain, Dean returned as a demon and a Knight of Hell loyal only to himself. He was then cured by his brother using purified blood. Eventually, the Mark was removed, but the price was that the Darkness has now been released into the world, something Dean tried to avoid. Dean and his brother soon met God who returned to help put an end to the danger to the world. During this time, Dean got through to God about not sacrificing himself and The Darkness about not destroying all of reality and helped them reconcile. As a reward, Dean was given back his mother and was able to return to his usual style of hunting with his family.",
  },
  {
    src: "https://i.pinimg.com/564x/40/ac/fc/40acfc6afc111274480f71e482e0acfa.jpg",
    title: "Sam Winchester",
    content:
      "Samuel Sam William[1] Winchester (b. May 2, 1983) was a hunter as well as a Man of Letters, along with his older brother Dean. He is one of the main protagonists of Supernatural. Both Sam and Dean are related to the Winchester and Campbell families - a Letters family and a Hunting family respectively. The pair also shares a bloodline with Cain and Abel. Because of this, Sam was predestined to be the true vessel of the fallen archangel Lucifer (whilst Dean was Michael's). Sam is friends with angel Castiel, Prophet Kevin Tran, the demon Meg and former lover-turned-enemy of demon Ruby. He is also the occasional reluctant ally of demon Crowley and for a time was forced to be an unknowing and unwilling vessel for the angel Gadreel (before expelling him). After the demon Azazel killed their mother, Mary, both Sam and Dean were raised in the hunting life by their father John. Sam left the hunting life to pursue a career in law, and most likely would have married his college sweetheart Jessica Moore. At the series' start, Sam was reluctant to start hunting again. When Jessica was killed, he was pushed back into the hunting life. However, he has been repeatedly known to try and back out of hunting in the hope of finally having a normal life as he wanted. After Sam's quest to remove the Mark of Cain unleashed the Darkness upon the world, Sam was forced to confront the consequences of his actions. For Sam, the situation worsened when Lucifer manipulated the situation to escape in the vessel of Castiel. Sam was left torn between using Lucifer to help battle the Darkness as Castiel wished and his own traumas and the resulting desire to be rid of the rogue archangel as a result.Following the reconciliation of the Darkness and God, Sam was abducted by agents of the British Men of Letters and tortured. During this time, Sam faced a surprise reunion with his resurrected mother, the return of Lucifer to evil and the draw of the promises of the British Men of Letters to rid the world of monsters. The situation was further exasperated when Lucifer conceived a Nephilim child before his apparent defeat and return to the Cage. With the British Men of Letters threat growing, Sam was forced into a leadership role to end the threat, but suffered losses while battling Lucifer for control of his child.With the losses of Crowley and Castiel and with Mary Winchester trapped in the Apocalypse World with Lucifer, Sam struggled to find a way to rescue his mother while dealing with Lucifer's son Jack and Dean's growing depression, aided by Castiel's subsequent resurrection. He was also forced to contend with the threat from the last Prince of Hell Asmodeus. However, after Jack got trapped in Apocalypse World as well, Sam fell into a depression of his own, only lightened when a way was found to rescue Mary and Jack.",
  },
  {
    src: "https://i.pinimg.com/564x/12/05/fb/1205fb2e109b7793beaf4d8239076dbc.jpg",
    title: "Bobby Singer",
    content:
      " Bobby was born in 1950. Bobby grew up in an abusive environment. His father, Ed was an alcoholic who constantly yelled at him and his mother. One day when his father was hitting his mother, Bobby pulled out a rifle and shot Ed. His father's last words stuck with him, 'You break everything you touch.'[2] Years later he got married to Karen. Three days before Karen was possessed and was killed, the two had a fight about children and did not talk after. Bobby became a hunter after he had to kill his wife Karen Singer when she was possessed by a demon. Rufus Turner is the hunter who exorcised the demon and helped cover up Karen's death. It was Rufus who introduced Bobby to the world of the supernatural, and they hunted together for many years until a hunt went wrong in Omaha around 1993. Sometime in December 1991,[3] Sam mentions 'uncle Bobby,' meaning that Bobby met John Winchester and started helping him take care of Sam and Dean some time before Christmas of 1991. He took the boys on hunting trips and even played catch with Dean in the park, as well as giving Sam the amulet that he (Sam) gave to Dean for Christmas. While seeking Bobby's refuge from Meg and Azazel, Dean mentioned that the last time he and Sam saw Bobby (it is unknown wh",
  },
];
